customhost = "employees.c7kn95m0dr8w.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employees"
custombucket = "simhongliemployees"
customregion = "us-east-1"
